/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as authenticatedRouteRouteImport } from './routes/(authenticated)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authenticatedDashboardRouteImport } from './routes/(authenticated)/dashboard'
import { Route as authenticatedSpacesIndexRouteImport } from './routes/(authenticated)/spaces/index'
import { Route as authenticatedScratchpadIndexRouteImport } from './routes/(authenticated)/scratchpad/index'
import { Route as authenticatedInboxIndexRouteImport } from './routes/(authenticated)/inbox/index'
import { Route as authenticatedCaptureIndexRouteImport } from './routes/(authenticated)/capture/index'
import { Route as authenticatedSpacesIdRouteImport } from './routes/(authenticated)/spaces/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedRouteRoute = authenticatedRouteRouteImport.update({
  id: '/(authenticated)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authenticatedDashboardRoute = authenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedSpacesIndexRoute =
  authenticatedSpacesIndexRouteImport.update({
    id: '/spaces/',
    path: '/spaces/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedScratchpadIndexRoute =
  authenticatedScratchpadIndexRouteImport.update({
    id: '/scratchpad/',
    path: '/scratchpad/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedInboxIndexRoute = authenticatedInboxIndexRouteImport.update({
  id: '/inbox/',
  path: '/inbox/',
  getParentRoute: () => authenticatedRouteRoute,
} as any)
const authenticatedCaptureIndexRoute =
  authenticatedCaptureIndexRouteImport.update({
    id: '/capture/',
    path: '/capture/',
    getParentRoute: () => authenticatedRouteRoute,
  } as any)
const authenticatedSpacesIdRoute = authenticatedSpacesIdRouteImport.update({
  id: '/spaces/$id',
  path: '/spaces/$id',
  getParentRoute: () => authenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/capture': typeof authenticatedCaptureIndexRoute
  '/inbox': typeof authenticatedInboxIndexRoute
  '/scratchpad': typeof authenticatedScratchpadIndexRoute
  '/spaces': typeof authenticatedSpacesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof authenticatedDashboardRoute
  '/spaces/$id': typeof authenticatedSpacesIdRoute
  '/capture': typeof authenticatedCaptureIndexRoute
  '/inbox': typeof authenticatedInboxIndexRoute
  '/scratchpad': typeof authenticatedScratchpadIndexRoute
  '/spaces': typeof authenticatedSpacesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(authenticated)': typeof authenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/(authenticated)/dashboard': typeof authenticatedDashboardRoute
  '/(authenticated)/spaces/$id': typeof authenticatedSpacesIdRoute
  '/(authenticated)/capture/': typeof authenticatedCaptureIndexRoute
  '/(authenticated)/inbox/': typeof authenticatedInboxIndexRoute
  '/(authenticated)/scratchpad/': typeof authenticatedScratchpadIndexRoute
  '/(authenticated)/spaces/': typeof authenticatedSpacesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/spaces/$id'
    | '/capture'
    | '/inbox'
    | '/scratchpad'
    | '/spaces'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/spaces/$id'
    | '/capture'
    | '/inbox'
    | '/scratchpad'
    | '/spaces'
  id:
    | '__root__'
    | '/'
    | '/(authenticated)'
    | '/login'
    | '/(authenticated)/dashboard'
    | '/(authenticated)/spaces/$id'
    | '/(authenticated)/capture/'
    | '/(authenticated)/inbox/'
    | '/(authenticated)/scratchpad/'
    | '/(authenticated)/spaces/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authenticatedRouteRoute: typeof authenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)': {
      id: '/(authenticated)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(authenticated)/dashboard': {
      id: '/(authenticated)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof authenticatedDashboardRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/spaces/': {
      id: '/(authenticated)/spaces/'
      path: '/spaces'
      fullPath: '/spaces'
      preLoaderRoute: typeof authenticatedSpacesIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/scratchpad/': {
      id: '/(authenticated)/scratchpad/'
      path: '/scratchpad'
      fullPath: '/scratchpad'
      preLoaderRoute: typeof authenticatedScratchpadIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/inbox/': {
      id: '/(authenticated)/inbox/'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof authenticatedInboxIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/capture/': {
      id: '/(authenticated)/capture/'
      path: '/capture'
      fullPath: '/capture'
      preLoaderRoute: typeof authenticatedCaptureIndexRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
    '/(authenticated)/spaces/$id': {
      id: '/(authenticated)/spaces/$id'
      path: '/spaces/$id'
      fullPath: '/spaces/$id'
      preLoaderRoute: typeof authenticatedSpacesIdRouteImport
      parentRoute: typeof authenticatedRouteRoute
    }
  }
}

interface authenticatedRouteRouteChildren {
  authenticatedDashboardRoute: typeof authenticatedDashboardRoute
  authenticatedSpacesIdRoute: typeof authenticatedSpacesIdRoute
  authenticatedCaptureIndexRoute: typeof authenticatedCaptureIndexRoute
  authenticatedInboxIndexRoute: typeof authenticatedInboxIndexRoute
  authenticatedScratchpadIndexRoute: typeof authenticatedScratchpadIndexRoute
  authenticatedSpacesIndexRoute: typeof authenticatedSpacesIndexRoute
}

const authenticatedRouteRouteChildren: authenticatedRouteRouteChildren = {
  authenticatedDashboardRoute: authenticatedDashboardRoute,
  authenticatedSpacesIdRoute: authenticatedSpacesIdRoute,
  authenticatedCaptureIndexRoute: authenticatedCaptureIndexRoute,
  authenticatedInboxIndexRoute: authenticatedInboxIndexRoute,
  authenticatedScratchpadIndexRoute: authenticatedScratchpadIndexRoute,
  authenticatedSpacesIndexRoute: authenticatedSpacesIndexRoute,
}

const authenticatedRouteRouteWithChildren =
  authenticatedRouteRoute._addFileChildren(authenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authenticatedRouteRoute: authenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
